generate_requirements:
  stage: pre-test
  image:
    name: $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA-python3.8
    entrypoint: [""]
  script:
    - poetry export --format requirements.txt --output requirements.txt
  artifacts:
    paths:
      - requirements.txt