include:
  - template: Security/License-Scanning.gitlab-ci.yml

license_scanning:
  stage: test
  dependencies:
    - generate_requirements

variables:
  LM_PYTHON_VERSION: 3
  LICENSE_FINDER_CLI_OPTS: "--enabled-package-managers=pip --python-version=3 --decisions-file=dependency_decisions.yml"